version: "3.9"

services:
  server:
    build: ./server
    ports:
      - "80:3000"

  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/nginx.conf
