version: "3.9"

services:
  server:
    build: ./server
    ports:
      - "80:3000"

  db:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --lower_case_table_names=2
    ports:
      - "3306:3306"
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: ./db/.env
    environment:
      TZ: Asia/Seoul

  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/nginx.conf
